name: WordPress Plugin Release

on:
  push:
    branches:
      - main

jobs:
  mahoee-tracking:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'Release') && endsWith(github.event.head_commit.message, 'mahoee-tracking') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, zip, intl, curl

      - name: Install Composer Dependencies
        run: |
          cd mahoee-tracking
          composer install

      - name: Get Plugin Version
        id: get_version_tracking
        run: |
          version=$(grep -o 'Version: [0-9.]\+' mahoee-tracking/mahoee-tracking.php | awk '{print $2}')
          echo "version=${version}" >> $GITHUB_ENV
          echo "##[set-output name=version;]${version}"

      - name: Create zip file of mahoee-tracking
        run: |
          zip -r mahoee-tracking-${{ steps.get_version_tracking.outputs.version }}.zip mahoee-tracking

      - name: Create Release for mahoee-tracking
        id: create_release_tracking
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: mahoee-tracking-${{ steps.get_version_tracking.outputs.version }}
          release_name: Mahoee Tracking ${{ steps.get_version_tracking.outputs.version }}
          body: Release ${{ steps.get_version_tracking.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_tracking.outputs.upload_url }}
          asset_path: ./mahoee-tracking-${{ steps.get_version_tracking.outputs.version }}.zip
          asset_name: mahoee-tracking-${{ steps.get_version_tracking.outputs.version }}.zip
          asset_content_type: application/zip

  mahoee-acme:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'Release') && endsWith(github.event.head_commit.message, 'mahoee-acme') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, zip, intl, curl

      - name: Install Composer Dependencies
        run: |
          cd mahoee-acme
          composer install

      - name: Get Plugin Version
        id: get_version_acme
        run: |
          version=$(grep -o 'Version: [0-9.]\+' mahoee-acme/mahoee-acme.php | awk '{print $2}')
          echo "version=${version}" >> $GITHUB_ENV
          echo "##[set-output name=version;]${version}"

      - name: Create zip file of mahoee-acme
        run: |
          zip -r mahoee-acme-${{ steps.get_version_acme.outputs.version }}.zip mahoee-acme

      - name: Create Release for mahoee-acme
        id: create_release_acme
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: mahoee-acme-${{ steps.get_version_acme.outputs.version }}
          release_name: Mahoee ACME ${{ steps.get_version_acme.outputs.version }}
          body: Release ${{ steps.get_version_acme.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_acme.outputs.upload_url }}
          asset_path: ./mahoee-acme-${{ steps.get_version_acme.outputs.version }}.zip
          asset_name: mahoee-acme-${{ steps.get_version_acme.outputs.version }}.zip
          asset_content_type: application/zip
